# Generated by Django 2.2 on 2021-05-23 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210522_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='total_horas',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
