# Generated by Django 4.1.3 on 2022-12-31 19:09

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habilidades',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Experiência',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField(default=0)),
                ('descricao', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('porcetagem', models.IntegerField(default=0, help_text='Porcetagem da Experiência')),
                ('pontuacao', models.IntegerField(default=0, help_text='Pontuação da Experiência')),
                ('total', models.IntegerField(default=0, help_text='total da Experiência do nivel')),
                ('user', models.ManyToManyField(blank=True, related_name='experiências', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Experiência',
                'verbose_name_plural': 'Experiências',
            },
        ),
    ]
