# Generated by Django 4.1.3 on 2022-12-31 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_habilidades_id_experiência'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Experiência',
            new_name='Experiencia',
        ),
    ]
