# Generated by Django 2.2 on 2021-05-23 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210522_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='total_horas',
            field=models.CharField(default='00:00:00', max_length=50),
        ),
    ]
