# Generated by Django 4.1.3 on 2022-12-31 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_experiência_experiencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiencia',
            old_name='porcetagem',
            new_name='porcentagem',
        ),
    ]
