# Generated by Django 4.1.3 on 2022-12-31 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_experiencia_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencia',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
