# Generated by Django 2.2 on 2021-05-23 01:51

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genre', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=150)),
                ('Descricao', models.TextField()),
                ('Publish', models.DateTimeField(blank=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Popularity', models.IntegerField(default=0)),
                ('Poster', models.URLField(blank=True)),
                ('Poster_url', models.URLField(blank=True)),
                ('Edicao', models.IntegerField()),
                ('Editora', models.CharField(blank=True, max_length=150)),
                ('Linguagem', models.CharField(blank=True, max_length=150)),
                ('Paginas', models.IntegerField()),
                ('ISBN', models.CharField(max_length=90)),
                ('Average_Rating', models.CharField(blank=True, default=0, max_length=5)),
                ('Average_Count', models.CharField(blank=True, default=0, max_length=100)),
                ('Votes_Count', models.CharField(blank=True, default=0, max_length=100)),
                ('Likes', models.IntegerField(blank=True, default=0, null=True)),
                ('total_horas', models.CharField(max_length=150)),
                ('Autor', models.ManyToManyField(blank=True, to='author.Author')),
                ('Genero', models.ManyToManyField(blank=True, to='genre.Genre')),
                ('user', models.ManyToManyField(blank=True, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('rate', models.IntegerField()),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livros.Ebook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_livro_review', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, unique=True)),
                ('img', models.URLField()),
                ('adicionado', models.DateTimeField(auto_now_add=True, null=True)),
                ('livro', models.ManyToManyField(to='livros.Ebook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_playlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livros.Ebook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_livro_like', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Leitura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(choices=[(0, 'PROJETO'), (1, 'LENDO'), (2, 'PAUSADA'), (3, 'CONCLUíDA')], default=0, max_length=40)),
                ('inicio', models.DateTimeField(auto_now_add=True, null=True)),
                ('termino', models.DateTimeField(null=True)),
                ('duracao_total', models.DurationField(default=datetime.timedelta(0), null=True)),
                ('paginas', models.IntegerField(blank=True, default=0, null=True)),
                ('resenha', models.TextField(blank=True, null=True)),
                ('complete_per', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livro', to='livros.Ebook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_leitura', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leitura',
            },
        ),
        migrations.CreateModel(
            name='Favoritos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adicionado', models.DateTimeField(auto_now_add=True, null=True)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='livros.Ebook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favoritos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
