# Generated by Django 2.2 on 2021-05-23 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leitura',
            name='pre_requisito',
            field=models.ManyToManyField(related_name='pre_requisitos', to='livros.Leitura'),
        ),
    ]
