# Generated by Django 2.2 on 2021-05-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0004_auto_20210530_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='Average_Count',
            field=models.CharField(blank=True, default=0, max_length=100),
        ),
    ]
