# Generated by Django 2.2 on 2021-05-31 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0006_auto_20210530_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leitura',
            name='termino',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
