# Generated by Django 2.2 on 2021-05-31 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0007_auto_20210531_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leitura',
            name='paginas',
            field=models.IntegerField(default=0),
        ),
    ]
