# Generated by Django 2.2 on 2021-05-23 01:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actor', '0001_initial'),
        ('director', '0001_initial'),
        ('genre', '0002_genre_livros'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=200)),
                ('Year', models.DateTimeField(auto_now_add=True)),
                ('Publish', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Status', models.CharField(blank=True, choices=[('cartaz', 'Cartaz'), ('em breve', 'Em Breve'), ('lançamento', 'Lançamento'), ('geral', 'Geral'), ('novo', 'Novo')], default='geral', max_length=140)),
                ('Popularity', models.IntegerField()),
                ('Released', models.DateTimeField(auto_now_add=True)),
                ('Runtime', models.CharField(blank=True, max_length=25)),
                ('Description', models.CharField(blank=True, max_length=900)),
                ('Language', models.CharField(blank=True, max_length=300)),
                ('Country', models.CharField(blank=True, max_length=100)),
                ('Awards', models.CharField(blank=True, max_length=250)),
                ('Poster', models.URLField(blank=True)),
                ('Poster_url', models.URLField(blank=True)),
                ('Average_Rating', models.CharField(blank=True, max_length=5)),
                ('Average_Count', models.CharField(blank=True, max_length=100)),
                ('Votes_Count', models.CharField(blank=True, max_length=100)),
                ('Budget', models.IntegerField(blank=True, default=0)),
                ('Revenue', models.IntegerField(blank=True, default=0)),
                ('imdbID', models.CharField(blank=True, max_length=100)),
                ('Filmes_views', models.IntegerField(blank=True, default=0)),
                ('Video', models.IntegerField(blank=True, default=0)),
                ('Trailler', models.CharField(blank=True, max_length=100, null=True)),
                ('Watched', models.IntegerField(blank=True, default=0)),
                ('Type', models.CharField(blank=True, max_length=100)),
                ('Actors', models.ManyToManyField(blank=True, to='actor.Actor')),
                ('Directors', models.ManyToManyField(blank=True, to='director.Director')),
                ('Genre', models.ManyToManyField(blank=True, to='genre.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('rating', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Trailler',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_movie_trailler', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('media', models.CharField(max_length=10)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_movie_review', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='Ratings',
            field=models.ManyToManyField(blank=True, to='movie.Rating'),
        ),
        migrations.AddField(
            model_name='movie',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='usename', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_movie_like', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
