# Generated by Django 4.1.3 on 2022-12-31 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='O titulo da categoria prestação de serviço', max_length=150)),
                ('slug', models.SlugField()),
                ('descricao', models.TextField(blank=True, help_text='A descricição da categoria')),
                ('quantidade', models.IntegerField(default=0, help_text='A quantidade de livros nesta categoria')),
                ('ranking', models.IntegerField(default=0, help_text='A Classificação que esta a categoria')),
                ('popularidade', models.IntegerField(default=0, help_text='A Popularidade da categoria ')),
                ('is_active', models.BooleanField(default=False, help_text='se tem genero cadastrado')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('slug', models.SlugField()),
                ('descricao', models.TextField(blank=True, help_text='A descricição da categoria', null=True)),
                ('quantidade', models.IntegerField(default=0, help_text='A quantidade de livros deste genero')),
                ('ranking', models.IntegerField(default=0, help_text='A Classificação que esta esse genero')),
                ('popularidade', models.IntegerField(default=0, help_text='A Popularidade deste genero ')),
                ('icone', models.CharField(default='fas fa-book-reader', help_text='icone', max_length=150)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='genero.categoria')),
            ],
            options={
                'verbose_name': 'Genero',
                'verbose_name_plural': 'Generos',
            },
        ),
    ]
