# Generated by Django 4.1.3 on 2022-12-31 12:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('livros', '0001_initial'),
        ('genero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genero',
            name='livros',
            field=models.ManyToManyField(blank=True, related_name='genero_livros', to='livros.ebook'),
        ),
        migrations.AddField(
            model_name='genero',
            name='usuarios',
            field=models.ManyToManyField(blank=True, related_name='categorias', to=settings.AUTH_USER_MODEL),
        ),
    ]
