# Generated by Django 4.1.3 on 2022-12-31 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genero', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genero',
            name='icone',
        ),
        migrations.AddField(
            model_name='categoria',
            name='icone',
            field=models.CharField(default='fas fa-book-reader', help_text='icone', max_length=150),
        ),
    ]
