# Generated by Django 2.2 on 2021-05-23 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
        ('genre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='livros',
            field=models.ManyToManyField(blank=True, related_name='genero_livros', to='livros.Ebook'),
        ),
    ]
