# Generated by Django 4.1.3 on 2022-12-31 12:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=70, unique=True)),
                ('logo', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(null=True)),
                ('descricao', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('idioma', models.CharField(choices=[('português', 'Português'), ('inglês', 'Inglês'), ('espanhol', 'Espanhol'), ('italiano', 'Italiano'), ('francês', 'Francês'), ('alemão', 'Alemão'), ('catalão', 'Catalão')], default='inglês', max_length=150)),
            ],
        ),
    ]
