# Generated by Django 4.1.3 on 2022-12-31 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editora', '0001_initial'),
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='editora',
            name='livros',
            field=models.ManyToManyField(blank=True, related_name='editora_ebook', to='livros.ebook'),
        ),
    ]
